# crontab syntax http://en.wikipedia.org/wiki/Cron

ProductCheckJob:
  every: 100s
  class: ProductCheckJob
  queue: daily_live_product_check
  args: tresbien
  description: product_check job, with the store_name hardcoded
               # to tresbien, and must be manually queued
